// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import { group } from "k6";
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";

// export let options = {
//   executor: "constant-vus",
//   duration: "1m",
//   vus: 1
// };

export let options = {
    vus: 1, // 시작 가상 사용자 수
    stages: [
        { duration: "4m", target: 1000 }, // 30초 동안 가상 사용자 수를 1초당 1씩 증가시키면서 50까지 도달
        { duration: "2m", target: 1000 }, // 1분행 동안 가상 사용자 수를 유지
        { duration: "4m", target: 0 } // 30초 동안 가상 사용자 수를 1초당 1씩 감소시키면서 0으로 도달
    ],
    // thresholds: {
    //     http_req_duration: ["p(95)<500"], // 95% 이상의 요청 시간이 500ms 이내인지 확인하는 threshold
    // },
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});
const token = "token"
const host = 'http://localhost:3000'

export default function() {
  group("App", function() {
    group("테스트1", function() {
      postman[Request]({
        name: "1",
        id: "ea22b582-b166-44cf-ae9e-6dcfd91c3454",
        method: "GET",
        address: `${host}/api/main`,
        headers: {
          token: token
        }
      });
    });


    group("테스트2", function() {
      postman[Request]({
        name: "2",
        id: "adcaf1a8-922c-413d-b8c4-c8017d8248466",
        method: "POST",
        address: `${host}/api/detail`,
        headers: {
          token: token
        }
      });
    });
  });
}

export function handleSummary(data) {
    return {
        "summary.html": htmlReport(data),
    };
}
